version: "3"
networks:
  loki:
services:
  #################
  loki0:
    image: grafana/loki:2.4.0
    volumes:
      - /Users/emagradze/CodeArea/grafana-loki-dockerized/loki_0:/etc/loki
    ports:
      - "3100:3100"
    restart: unless-stopped
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - loki
  promtail0:
    image: grafana/promtail:2.4.0
    volumes:
      - /var/log:/var/log
      - /Users/emagradze/CodeArea/grafana-loki-dockerized/promtail_0:/etc/promtail
    # ports:
    #   - "1514:1514" # this is only needed if you are going to send syslogs
    restart: unless-stopped
    command: -config.file=/etc/promtail/promtail-config.yml
    networks:
      - loki
  #################
  loki1:
    image: grafana/loki:2.4.0
    volumes:
      - /Users/emagradze/CodeArea/grafana-loki-dockerized/loki_1:/etc/loki
    ports:
      - "3101:3101"
    restart: unless-stopped
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - loki
  promtail1:
    image: grafana/promtail:2.4.0
    volumes:
      - /var/log:/var/log
      - /Users/emagradze/CodeArea/grafana-loki-dockerized/promtail_1:/etc/promtail
    # ports:
    #   - "1514:1514" # this is only needed if you are going to send syslogs
    restart: unless-stopped
    command: -config.file=/etc/promtail/promtail-config.yml
    networks:
      - loki
  #################
  loki2:
    image: grafana/loki:2.4.0
    volumes:
      - /Users/emagradze/CodeArea/grafana-loki-dockerized/loki_2:/etc/loki
    ports:
      - "3102:3102"
    restart: unless-stopped
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - loki
  promtail2:
    image: grafana/promtail:2.4.0
    volumes:
      - /var/log:/var/log
      - /Users/emagradze/CodeArea/grafana-loki-dockerized/promtail_2:/etc/promtail
    # ports:
    #   - "1514:1514" # this is only needed if you are going to send syslogs
    restart: unless-stopped
    command: -config.file=/etc/promtail/promtail-config.yml
    networks:
      - loki
  #################
  loki3:
    image: grafana/loki:2.4.0
    volumes:
      - /Users/emagradze/CodeArea/grafana-loki-dockerized/loki_3:/etc/loki
    ports:
      - "3103:3103"
    restart: unless-stopped
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - loki
  promtail3:
    image: grafana/promtail:2.4.0
    volumes:
      - /var/log:/var/log
      - /Users/emagradze/CodeArea/grafana-loki-dockerized/promtail_3:/etc/promtail
    # ports:
    #   - "1514:1514" # this is only needed if you are going to send syslogs
    restart: unless-stopped
    command: -config.file=/etc/promtail/promtail-config.yml
    networks:
      - loki
  grafana:
    image: grafana/grafana:latest
    user: "1000"
    volumes:
    - /Users/emagradze/CodeArea/grafana-loki-dockerized/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - loki
