apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: grafana-volume
  namespace: grafana
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
reclaimPolicy: Delete
allowVolumeExpansion: true
mountOptions:
  - debug
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-volume-claim
  namespace: grafana
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: grafana-volume
  resources:
    requests:
      storage: 45Gi