apiVersion: v1
kind: Service
metadata:
  name: grafana-service-lb
  namespace: grafana
spec:
  type: LoadBalancer
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
