apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: loki02
  name: loki02
  namespace: grafana
spec:
  selector:
    matchLabels:
      app: loki02
  template:
    metadata:
      labels:
        app: loki02
    spec:
      securityContext:
        fsGroup: 472
        supplementalGroups:
          - 0
      containers:
        - name: loki02
          image: grafana/loki:main
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3100
              name: http-loki
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3100
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 250m
              memory: 750Mi
          volumeMounts:
            - mountPath: /tmp/loki
              name: loki02-deployment-pv
      volumes:
        - name: loki02-deployment-pv
          persistentVolumeClaim:
            claimName: loki-volume-claim-01
---
apiVersion: v1
kind: Service
metadata:
  name: loki02
  namespace: grafana
spec:
  ports:
    - port: 3100
      protocol: TCP
      targetPort: http-loki
  selector:
    app: loki02
  sessionAffinity: None
  type: LoadBalancer
