apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: loki-volume
  namespace: grafana
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
reclaimPolicy: Delete
allowVolumeExpansion: true
mountOptions:
  - debug
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-volume-claim-01
  namespace: grafana
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: loki-volume
  resources:
    requests:
      storage: 45Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-volume-claim-02
  namespace: grafana
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: loki-volume
  resources:
    requests:
      storage: 45Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-volume-claim-03
  namespace: grafana
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: loki-volume
  resources:
    requests:
      storage: 45Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-volume-claim-04
  namespace: grafana
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: loki-volume
  resources:
    requests:
      storage: 45Gi
